name: Forge Coverage

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

permissions: write-all

jobs:
  check:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-e15e33a07c0920189fc336391f538c3dad53da73

      - name: Run coverage
        run: |
          forge coverage --report lcov
        id: coverage

      - name: Install lcov and filter report
        run: |
          sudo apt-get install -y lcov
          lcov --remove ./lcov.info -o ./lcov.info 'script/*' 'test/*'

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: lcov.info
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
