name: Slither Analysis

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: "3.11.6"
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: "x64"

      - name: Install solc with solc-select
        run: |
          python -m pip install slither-analyzer
          python -m pip install solc-select
          solc-select install 0.8.23
          solc-select use 0.8.23

      - name: Run Slither
        run: |
          forge build --build-info --skip '*/test/**' --skip '*/script/**' --force && slither --compile-force-framework foundry --ignore-compile --sarif results.sarif --config-file slither.config.json --fail-high .
          echo "sarif=results.sarif" >> "$GITHUB_OUTPUT"
        id: slither
